### ISSUE TITLE
Button not showing in Wordpress 5.8.1

### ISSUE THREAD

**Issue by jhonny-oliveira** [salvatorecordiano/re-add-text-justify-button#2]
Hi!

I have installed this plugin in Wordpress 5.8.1, but the button is not showing.

Can you help?

Thank you!
Jhonny

**Comment by salvatorecordiano** [comment]
Hi @jhonny-oliveira,
please install https://wordpress.org/plugins/classic-editor/. 
It's required to use Re-Add Text Justify Button plugin.

Thanks,
Salvo

**Comment by jhonny-oliveira** [comment]
Tahnk you @salvatorecordiano !
